# -*- coding: utf-8 -*-
"""Challenge_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SfsaPfxA_xSfqCwpRQw_ouk-DFIj77W4

# Challenge_2

1. Demonstrate how to create simple and multi-line strings, and check whether a string can change after its creation.
"""

str_1 = "Hello!"   # a simple, single line string
str_2 = """Hello,
How 
are
you?
"""        # a multi-line string

print(str_1)       # printing a single line string
print(str_2)       # printing a multi-line string

str_1[0] = "y"   # attempting to change a string
print(str_1)     # the error justifies that the string as a datastructure is 'immutable'

"""2. For a given string ‘Hello World!’, extract the following:

a) H W
b) o o
c) llorld
d) !dlroW olleH
e) World!
f) Hello
"""

meri_string='Hello World!'

print(meri_string[0:1] + ' ' + meri_string[6:7] )    # a)  #proper use of string concatenation and extraction using string indices
print(meri_string[4:5]+ ' ' + meri_string[7:8])      # b)
print(meri_string[2:4] + meri_string[7:11])          # c)
print(meri_string[-1:-12])                           # d).  for printing the string in reverse order negative indices are intended to use
print(meri_string[6:])                               # e) 
print(meri_string[:5])                               # f)

"""3. For the following strings, determine which contain only alphabets, only digits, alphanumeric, which are in lowercase, and which are in uppercase. Also check whether str3 begins or ends with the word “Now”.

Str1 = ‘Welcome’

Str2 = ‘Hello World!’

Str3 = ‘Now is the best time ever! ‘

Str4 = ‘500017’

Str5 = ‘IPhone 6’
"""

#Strings for performing check-operations

Str1 = 'Welcome'
Str2 = 'Hello World!'
Str3 = 'Now is the best time ever!'
Str4 = '500017'
Str5 = 'IPhone 6'

#Str1
print('Str1 is alpha', Str1.isalpha)
print('Str1 is digit',Str1.isdigit)
print('Str1 is in lower case' , Str1.islower)
print('Str1 is in uppercase', Str1.isupper)
print('\n')
#Str2
print('Str2 is alpha', Str2.isalpha)
print('Str2 is digit',Str2.isdigit)
print('Str2 is in lower case' , Str2.islower)
print('Str2 is in uppercase', Str2.isupper)
print('\n')

#Str3
print('Str3 is alpha', Str3.isalpha)
print('Str3 is digit',Str3.isdigit)
print('Str3 is in lower case' , Str3.islower)
print('Str3 is in uppercase', Str3.isupper)
print('Str3 starts with "Now"', Str3.startswith('Now'))
print('Str3 ends with "Now"', Str3.endswith('Now'))
print('\n')

#Str4
print('Str4 is alpha', Str4.isalpha)
print('Str4 is digit',Str4.isdigit)
print('Str4 is in lower case' , Str4.islower)
print('Str4 is in uppercase', Str4.isupper)
print('\n')

#Str5
print('Str5 is alpha', Str5.isalpha)
print('Str5 is digit',Str5.isdigit)
print('Str5 is in lower case' , Str5.islower)
print('Str5 is in uppercase', Str5.isupper)

"""4. Accept a sentence from the user. Convert the case of the input into title case."""

sentence = input("Enter a Sentence: ")     #taking a sentence as input from the user
print(sentence.title())                    #returning the output in 'title case'

"""5. Write a program that reads an integer from the user. Then your program should display a message indicating whether the integer is even or odd."""

num = int(input("Enter a positive integer: "))         #taking input from the user

if num%2==0:                                           #condition to check if a number is even
  print("The number you entered:", num ,", is even.")

else:                                                  # a number can either be odd or an even, hence 'elif' is not used
  print("The number you entered:" , num , ", is odd.")

"""6. Create a program that reads a letter of the alphabet from the user. If the user enters a, e, i, o or u then your program should display a message indicating that the entered letter is a vowel. Otherwise, the program should display a message that the entered letter is a consonant"""

alpha = input("Enter an Alphabet in 'Lowercase': ")             #taking in input from the user.

if alpha in ['a','e','i','o','u']:                           #condition to check for equality in a set to find a vowel.
  print("The alphabet you entered:", alpha, ", is a vowel.")

else:                                                        # an alphabet can either be a vowel or a consonent and hence 'elif' is not used.
  print("The alphabet you entered:", alpha, ", is a consonent." )

"""7. The length of a month varies from 28 to 31 days. Create a program that reads the name of a month from the user as a string. Then your program should display the number of days in that month. Display “28 or 29 days” for February so that leap years is addressed."""

month = input("Enter name of a month in 'Lwercase' to calculate its number of days: ")                          #taking in input from the user.

if month in ['january','march','may','july','august','october','december']:                                     #checking for months with '31' days
  print("The number of days in the month that you entered: ",month,", is 31.")

elif month in ['april','june','september','november']:                                                          #checking for months with '30' days
  print("The number of days in the month that you entered: ",month,", is 30.")

else:                                                                                                           #checking if the month entered is 'february'
  print("The number of days in the month that you entered: ",month,", is 28 or 29.")

"""8. A triangle can be classified based on the lengths of its sides as equilateral, isosceles or scalene. All 3 sides of an equilateral triangle have the same length. An isosceles triangle has two sides that are the same length, and a third side that is a different length. If all of the sides have different lengths then the triangle is scalene. Write a program that reads the lengths of 3 sides of a triangle from the user. Display a message indicating the type of the triangle."""

side1 = int(input("Enter the length of 1st side of the triangle: "))             #taking in input for the 3 sides of a triangle, from the user.
side2 = int(input("Enter the length of 2nd side of the triangle: "))
side3 = int(input("Enter the length of 3rd side of the triangle: "))

print("\n")
if side1+side2>side3 and side1+side3>side2 and side2+side3>side1:                #condition to check if a trianle can be constructed with the given set of values for the 3 sides.           
  print("A triangle is possible.")

else:
  print("A triangle isn't possible.")  

print("\n")

if side1==side2 and side2==side3:                                                #conditions to check for the type of triangle
  print("The type of triangle is: 'Equilateral'.")

elif side1==side2 or side2==side3 or side3==side1:
  print("The type of triangle is: 'Isosceles'.")

else:
  print("The type of triangle is: 'Scalene'.")

"""9. The rules for determining whether or not a year is a leap year follow:

* Any year that is divisible by 400 is a leap year.
* Of the remaining years, any year that is divisible by 100 is not a leap year.
* Of the remaining years, any year that is divisible by 4 is a leap year.
* All other years are not leap years.

Write a program that reads a year from the user and displays a message indicating whether or not it is a leap year.
"""

year=int(input("Enter a 'Year', to check if it's a leap year or not: "))                 #taking in input from the user.

if year%400==0:                                                                          #checking for conditions to satisfy for a year to bea leap year.
  print("The year that you entered: ", year, "is a leap year.")

elif year%100==0:
  print("The year that you entered: ", year, "isn't a leap year.")  

elif year%4==0:
  print("The year that you entered: ", year, "is a leap year.")  

else:
  print("The year that you entered: ", year, "isn't a leap year.")

"""10. Write a program that computes the real roots of a quadratic function. Your program should begin by prompting the user for the values of a, b and c. Then it should display a message indicating the number of real roots, along with the values of the real roots (if any)."""

import math                                                                        # importing a library to calculate square root operation

print("A quadratic equation can be represented as: 'ax^2 + bx + c'")               #a message for the user.

a = int(input("Enter a value for 'a': "))                                          #taking in input from the user.
b = int(input("Enter a value for 'b': "))
c = int(input("Enter a value for 'c': "))

print("\n")
print("The quadratic equation you entered is: ", a,"x^2","+",b,"x","+",c)          #displaying the quadratic equation
print("\n")

value = ((b*b) - (4*a*c))

value1=math.sqrt(value)

root1 = (-b + (value1))/2*a
root2 = (-b - (value1))/2*a

if value==0:
  print("The quadratic equaion that you entered has both roots equal and they are: ", root1, root2)

elif value>0:
  print("The quadratic equaion that you entered has '2' unequal roots equal and they are: ", root1, root2)

else:
  print("The quadratic equaion that you entered has imaginery roots.")